resources:
- ../base
commonAnnotations:
  oncallPager: 800-hey-there
patches:
- target:
    kind: Deployment
    name: deploy
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx
    spec:
      template:
        spec:
          containers:
          - name: nginx
            image: nginx:1.7.9
