# kustomization.yaml contents
resources:
- ../base

commonLabels:
  kustomization: smp_replace

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx
  spec:
    template:
      spec:
        containers:
        - name: nginx
          image: nginx:1.7.9
          $patch: replace  
